name: crDroid Bug 
description: Report an issue with crDroid
title: "[BUG] "
labels: crDroid 14 bug, Pending
assignees: Android-Artisan 

body:
  - type: markdown
    attributes:
      value: |
       > [!NOTE]
       > This should be used only to report a bug relating to crDroid.

  - type: textarea
    id: autopilot-issue
    attributes:
      label: "Describe the Issue"
      description: Please describe your issue relating to crDroid.
      placeholder: Please describe your issue relating to crDroid.
    validations:
      required: true
      
  - type: textarea
    id: autopilot-reproduce
    attributes:
      label: "Reproduce the Issue"
      description: Describe how to accurately reproduce/exhibit the issue.
      placeholder: Please describe how to reproduce the issue.

  - type: textarea
    id: autopilot-expectation
    attributes:
      label: "Expectation"
      description: What did you expect to happen instead?
      placeholder: Please describe what you expected to happen.

  - type: markdown
    attributes:
      value: |
        ---
        # System Information

        Please provide details of your host system. The main points of interest are provided for you.


  - type: input
    id: host-kernel
    attributes:
      label: "Kernel"
    validations:
      required: true

  - type: dropdown
    id: host-device
    attributes:
      label: "Device"
      description: Please select the device you are using.
      options:
        - S20 4G/5G (x1s/lte)
        - S20+ 4G/5G (y2s/lte)
        - S20 Ultra (z3s)
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        ---
        # Information and logs

        Please enter the version of crDroid you are using, and any other relevant information.

  - type: input
    id: crdroid-version
    attributes:
      label: "Version"
      placeholder: vX.X
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Important Info

        > [!IMPORTANT]
        > Remember to redact any personal information, such as user names from file paths.


  - type: textarea
    id: logcat
    attributes:
      label: "Pleage generate a logcat while reproducing the issue"
      placeholder: Please paste the contents of the logcat file.
      render: xml


  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    id: additional
    attributes:
      label: "Additional Information"
      description: Please provide any additional information you think may be relevant.

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this issue. Please review the information you have provided and ensure it is correct before submitting the issue.
